# frozen_string_literal: true

source "https://rubygems.org"

gem 'rspec', '~> 3.10'
gem 'coderay', '~> 1.1', '>= 1.1.3'

gem 'logger', '~> 1.4', '>= 1.4.3'

#these maybe later...
#gem 'rack-test', '~> 2.0', '>= 2.0.2'
#gem 'sinatra', '~> 3.0', '>= 3.0.1'
#gem 'sequel', '~> 5.60', '>= 5.60.1'
#gem 'sqlite3', '~> 1.5'
